
name: Frontend React Lint

on:
  pull_request:
      branches:
        - sub-new
  push:
    branches:
      - sub-new
permissions:
  contents: read
  pull-requests: write
  
concurrency:
  group: frontend-lint-${{ github.ref }}
  cancel-in-progress: true

jobs:
  frontend-lint:
    name: React Lint & Build Check
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: frontend/package.json

      - name: Install dependencies
        run: npm ci

#      - name: Run ESLint
#        run: | 
#         npm run lint -- -f unix > eslint-report.txt
        continue-on-error: true
      - name: Run ESLint with Reviewdog
        if: github.event_name == 'pull_request'
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          filter_mode: diff_context
          fail_on_error: false
          workdir: frontend


      - name: Run Prettier check
        run: npx prettier --write .
        continue-on-error: true

      - name: Security audit
        run: npm audit --audit-level=high
        continue-on-error: true
        
      - name: Security audit fix
        run: npm audit fix --force
        continue-on-error: true

      - name: Build React app
        run: npm run build
