name: Frontend React Lint

on:
  pull_request:
      branches:
        - main
  push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write   #  REQUIRED FOR COMMENTS
  
concurrency:
  group: frontend-lint-${{ github.ref }}
  cancel-in-progress: true

jobs:
  frontend-lint:
    name: React Lint & Build Check
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: frontend/package.json

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint and save output
        working-directory: frontend
        run: |
          npm run lint > eslint-output.txt 2>&1 || true

      - name: Comment ESLint errors
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const text = fs.readFileSync('frontend/eslint.txt', 'utf8');
            if (text.trim()) {
              await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `âŒ ESLint Errors:\n\n\`\`\`\n${text}\n\`\`\``
            });
            }

      - name: Run ESLint with Reviewdog
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review # This puts comments on the code
          eslint_flags: ". --ext .js,.jsx,.ts,.tsx"


 #     - name: Run ESLint
 #       run: npm run lint
 #       continue-on-error: true

      - name: Run ESLint and capture output
        working-directory: frontend
        run: |
         npm run lint 2>&1 | tee eslint.txt
         continue-on-error: true


      - name: Run Prettier check
        run: npx prettier --write .
     #   continue-on-error: true

      - name: Security audit
        run: npm audit --audit-level=high
 #       continue-on-error: true
        
      - name: Security audit fix
        run: npm audit fix --force
#        continue-on-error: true

      - name: Build React app
        run: npm run build

   #   - name: ESLint with PR comments
   #     uses: reviewdog/action-eslint@v1
   #     with:
   #       github_token: ${{ secrets.GITHUB_TOKEN }}
   #       reporter: github-pr-review
   #       eslint_flags: "src/"
   #       workdir: frontend/
   #       filter_mode: nofilter

